# Generated by Django 4.0.4 on 2022-04-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_workout_intensity_alter_workout_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('Low', 'low'), ('Moderate', 'moderate'), ('High', 'high')], max_length=10),
        ),
    ]
