# Generated by Django 4.0.4 on 2022-04-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_workout_intensity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('exercise', models.CharField(max_length=50)),
                ('body', models.CharField(choices=[('Chest', 'Chest'), ('Arms', 'Arms'), ('Shoulders', 'Shoulders'), ('Back', 'Back'), ('Abs', 'Abs'), ('Legs', 'Legs')], max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='exercise',
            field=models.ManyToManyField(to='main_app.exercise'),
        ),
    ]
