# Generated by Django 4.0.4 on 2022-04-16 19:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_workout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='intensity',
            field=models.CharField(choices=[('low', 'low'), ('moderate', 'moderate'), ('high', 'high')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workout',
            name='rounds',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
